### ISSUE TITLE
Camera2 API support

### ISSUE THREAD

**Issue by bobobo1618** [sonyxperiadev/device-sony-lilac#6]
There are two problems with the Camera2 API implementation:

- RAW support is not present. This severely limits the usefulness of the camera as modern editing apps like Adobe's Lightroom or Google's Snapseed cannot be used. It's particularly crippling to the use of AOSP, which currently requires that users erase DRM keys which disables noise reduction. With no RAW support, users can't even use their own noise reduction.
- It doesn't support the full 19MP resolution of the sensor. The maximum image size that can be captured with Camera2 is 4K.

**Comment by jerpelea** [comment]
I wonder if you are using the AOSP software.
Am I right?

**Comment by jerpelea** [comment]
We will look into this issue

**Comment by jerpelea** [comment]
I just flashed and tested this device with AOSP and none of the reported issues can be replicated
This maked me wonder if you have the Sony software on your device

**Comment by bobobo1618** [comment]
I'm using Sony's retail release of Android and assuming it's based on this code, with some skins applied.

The Open Camera app has an option to use the Camera2 API. When this is enabled, the maximum available photo resolution is 3840x2160. The app also supports DNG (RAW) output. On the XZ1 Compact, this option is not available due to the Camera2 API not reporting it as present.

Are you saying this issue isn't present on AOSP?

Here are detailed repro instructions:

- Install [Open Camera](https://play.google.com/store/apps/details?id=net.sourceforge.opencamera)
- Open app
- Click gear icon in top/bottom right (depends on device orientation)
- Select "Use Camera2 API" (third option from bottom"
- App will restart
- Click the gear icon
- Select "Photo Settings"
- Select "Photo Resolution"
- Go back to settings
- Go to "More camera controls" 

Expected behaviour: "Photo Resolution" menu shows all resolutions up to and including 5096x3792, settings include the ability to save as DNG

Actual behaviour: Maximum resolution is 3840x2160. Option to save as DNG is not present.

Are you unable to reproduce this on an AOSP device? How were you able to capture a RAW image?

**Comment by kholk** [comment]
Unfortunately (and/or luckily, depending on how you see that), Sony's stock releases are not based on Open Devices' code.

Open Devices uses a different codebase, including not only a different ROM, but also a different kernel. These differences are also seen on the camera compartment, where the implementations are different between stock and Open Devices.
This repository has almost nothing to do with the factory firmware and is not used in any way to build the factory images for your phone.

Please note that Sony includes an app to report bugs in the stock ROMs: to report bugs related to that, use the provided app.



Anyway, to reply to the last question, this bug is not reproducible on Open Devices builds (meaning that it works, there's no such bug here).

Thanks!

**Comment by bobobo1618** [comment]
Ah, I see. Sorry for the trouble and thanks for confirming that it works on AOSP. In that case I might just give up on the retail ROM.

I find it very interesting that Sony maintains two codebases though.

**Comment by MartinX3** [comment]
I don't want to disturb the developers, but why is Sony developing 2 different code bases?
And why is Sony killing the camera at unlocking, while developing the camera code in the aosp code base?

Which benefits does Sony get from it?

I like the work you do and in my opinion it is the best a smartphone company can do, but I don't understand it.

**Comment by jerpelea** [comment]
The Open Devices software is developed from scratch, by the community, for community, based on the AOSP software and is completely decoupled from the official SW.
